### ISSUE TITLE
SQLException: Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by mibby** [BenCodez/VotingPlugin#489]
@Ben12345rocks VotingPlugin dev 575.

```
[01:18:48] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.17.3
[01:18:48] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[01:18:48] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[01:18:48] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:18:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadData(MySQL.java:461)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:132)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:18:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:18:48] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:18:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadData(MySQL.java:461)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumns(MySQL.java:257)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.checkColumn(MySQL.java:195)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.alterColumnType(MySQL.java:179)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:136)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:18:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:18:48] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:18:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.checkColumn(MySQL.java:196)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.alterColumnType(MySQL.java:179)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:136)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:18:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:18:48] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:18:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadData(MySQL.java:461)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumns(MySQL.java:257)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.addColumn(MySQL.java:163)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.checkColumn(MySQL.java:197)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.alterColumnType(MySQL.java:179)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:136)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:18:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:18:48] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:18:48] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:18:48] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:212)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.purgeOldPlayers(UserManager.java:187)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:375)
[01:18:48] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:18:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:18:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:18:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:18:48] [Server thread/ERROR]: Error occurred while enabling VotingPlugin v5.17.3 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getUuidsQuery(MySQL.java:412) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:214) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.purgeOldPlayers(UserManager.java:187) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:375) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-501]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-501]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-501]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-501]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-501]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-501]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:18:48] [Server thread/INFO]: [VotingPlugin] Disabling VotingPlugin v5.17.3
[01:18:48] [Timer-4/WARN]: Exception in thread "Timer-4" java.lang.NullPointerException
[01:18:48] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.Signs.Signs.storeSigns(Signs.java:80)
[01:18:48] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main$31.run(Main.java:692)
[01:18:48] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[01:18:48] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by mibby** [comment]
```
[01:18:58] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.IllegalAccessError: class com.zaxxer.hikari.pool.ProxyFactory tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V (com.zaxxer.hikari.pool.ProxyFactory is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4f469849; com.zaxxer.hikari.pool.HikariProxyStatement is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @204b3a09)
[01:18:58] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
[01:18:58] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:269)
[01:18:58] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
[01:18:58] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
[01:18:58] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
[01:18:58] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[01:18:58] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by BenCodez** [comment]
Configs? Server version?

**Comment by mibby** [comment]
Paper dev 501 (Spigot 1.13.2)
VotingPlugin dev 575

Config (removed mysql info)
https://paste.ubuntu.com/p/qGScNPGgGV/

I was using an earlier dev build fine so something must have broke in AdvancedCore if it's shaded into the plugin as a dependency.

**Comment by BenCodez** [comment]
Spigot version work?

**Comment by mibby** [comment]
Unfortunately not. It's an SQL issue.

**Comment by mibby** [comment]
@Ben12345rocks Related to this commit I believe.
https://github.com/Ben12345rocks/AdvancedCore/commit/601c37c35be639f485aafbc8c17cade8e0e9bf07

Downgraded to dev 551 and it still occurs. Downgraded to dev 544, start-up is fine.

**Comment by BenCodez** [comment]
Latest dev build should fix this.

I had an experimental change in a dev build. The latest version on spigot would be fine, I think

**Comment by mibby** [comment]
@Ben12345rocks Unfortunately that didn't seem to fix it. Still getting the error with dev 576.

```
[01:08:03] [Server thread/INFO]: [VotingPlugin] Enabling VotingPlugin v5.17.3
[01:08:03] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[01:08:03] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[01:08:03] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:08:03] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadData(MySQL.java:461)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:132)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:08:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:08:03] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:08:03] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadData(MySQL.java:461)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumns(MySQL.java:257)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.checkColumn(MySQL.java:195)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.alterColumnType(MySQL.java:179)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:136)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:08:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:08:03] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:08:03] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.checkColumn(MySQL.java:196)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.alterColumnType(MySQL.java:179)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:136)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:08:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:08:03] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:08:03] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.loadData(MySQL.java:461)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumns(MySQL.java:257)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.addColumn(MySQL.java:163)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.checkColumn(MySQL.java:197)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.alterColumnType(MySQL.java:179)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.<init>(MySQL.java:136)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook$10.run(AdvancedCoreHook.java:547)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread$ReadThread.run(Thread.java:49)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.Thread.Thread.run(Thread.java:103)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadUserAPI(AdvancedCoreHook.java:542)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadConfig(AdvancedCoreHook.java:317)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:369)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:08:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:08:03] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:08:03] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getMetaData(ResultSetImpl.java:2780)
[01:08:03] [Server thread/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getMetaData(HikariProxyResultSet.java)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getColumnsQueury(MySQL.java:269)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:212)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.purgeOldPlayers(UserManager.java:187)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:375)
[01:08:03] [Server thread/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[01:08:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:08:03] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[01:08:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:08:03] [Server thread/ERROR]: Error occurred while enabling VotingPlugin v5.17.3 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.getUuidsQuery(MySQL.java:412) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.clearCacheBasic(MySQL.java:214) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserManager.UserManager.purgeOldPlayers(UserManager.java:187) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.AdvancedCore.AdvancedCoreHook.loadHook(AdvancedCoreHook.java:375) ~[?:?]
	at com.Ben12345rocks.VotingPlugin.Main.onEnable(Main.java:711) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-503]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-503]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-503]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-503]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-503]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-503]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-503]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-503]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-503]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-503]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[01:08:03] [Server thread/INFO]: [VotingPlugin] Disabling VotingPlugin v5.17.3
[01:08:03] [Timer-4/WARN]: Exception in thread "Timer-4" java.lang.IllegalStateException: zip file closed
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:914)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:346)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.zip.ZipFile$1.getEntry(ZipFile.java:1120)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.jar.JarFile.getEntry0(JarFile.java:576)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:506)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[01:08:03] [Timer-4/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[01:08:03] [Timer-4/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:192)
[01:08:03] [Timer-4/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95)
[01:08:03] [Timer-4/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[01:08:03] [Timer-4/WARN]: 	at com.Ben12345rocks.VotingPlugin.Main$31.run(Main.java:692)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[01:08:03] [Timer-4/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```
```
[01:08:13] [Timer-3/WARN]: Exception in thread "Timer-3" java.lang.IllegalAccessError: class com.zaxxer.hikari.pool.ProxyFactory tried to access method com.zaxxer.hikari.pool.HikariProxyStatement.<init>(Lcom/zaxxer/hikari/pool/ProxyConnection;Ljava/sql/Statement;)V (com.zaxxer.hikari.pool.ProxyFactory is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2155db0e; com.zaxxer.hikari.pool.HikariProxyStatement is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3e78dcb7)
[01:08:13] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyFactory.getProxyStatement(ProxyFactory.java)
[01:08:13] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:269)
[01:08:13] [Timer-3/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
[01:08:13] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL.updateBatch(MySQL.java:542)
[01:08:13] [Timer-3/WARN]: 	at com.Ben12345rocks.VotingPlugin.AdvancedCore.UserStorage.mysql.MySQL$3.run(MySQL.java:142)
[01:08:13] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[01:08:13] [Timer-3/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by BenCodez** [comment]
Build 577?

**Comment by mibby** [comment]
Using dev 578, everything seems okay now.

**Comment by BenCodez** [comment]
That's good :)
